title: Голокрон
email: ornichola@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Небольшой блог для заметок и структурирования изучаемой информации.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ornichola
github_username:  ornichola

# Build settings
theme: jekyll-theme-hyde
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
