version: 0.2
author:
  name: ornichola


baseurl: ""
url: ""
title: Голокрон
description: >-
  Заметки об изучаемом материале.


plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"
excerpt_separator: <!--more-->

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
