version: 0.1
author:
  name: ornichola


baseurl: ""
url: ""
title: Голокрон
description: >-
  Заметки об изучаемом материале.


theme: jekyll-theme-hyde
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
paginate: 5


exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
